version: "3.9"
services:
  platform-be:
    build: .
    container_name: platform-be
    command: sh -c "/wait && node server.js"
    environment:
      WAIT_HOSTS: "platform-db:3306"
      WAIT_TIMEOUT: 60
    ports:
      - "3000:3000"
  platform-db:
    image: "mariadb:latest"
    container_name: platform-db
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    # healthcheck:
    #     test: ["CMD", "mysqladmin", "ping", "--silent"]
volumes:
  dbdata:
